name: Build TigerTag Studio

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, windows-latest]

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔧 Rebuild native modules
        run: npm run rebuild

      - name: 🛠 Build app
        run: npm run build

      - name: 📤 Upload artifacts
        uses: uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{ runner.os }} Build
          path: dist/